apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
   k8s-app: wavefront-proxy
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  selector:
    k8s-app: wavefront-proxy
